### ISSUE TITLE
Tarea: infografía de los sistemas numéricos 

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/infografia-Proyect-A16#1]
[24620193 Sistemas Numericos.pdf](https://github.com/user-attachments/files/16754024/24620193.Sistemas.Numericos.pdf)

**Comment by KarenIMont** [comment]
Redacción y Ortografía:12/14
Exposición de ideas Centrales:14/16
Organización de ideas centrales:12/14
Uso de Imágenes y Colores:14/14
Presentación Visual:12/14
Referencias:0/14
Presentación:12/14

Calificación Final: 15.2/20

**Comment by josealfredo79** [comment]
Revisado..
